### ISSUE TITLE
Possible overlap with EPITA.it?

### ISSUE THREAD

**Issue by utybo** [ItsAnas/awesome-epita#1]
Hi! This repository seems to be similar to EPITA.it (https://github.com/EpiDocs/epita.it / https://epita.it), is there anything that makes this list particularly different in some way?

Also, it would probably be nice to put a link to EPITA.it on the list :)

**Comment by ItsAnas** [comment]
Hi thank you for following up this project.

If I understand well, Epita.it tries to regroup every usefull resources about the school (Odysse, Intranet, Mastercorp, Algo TD etc.)
The goal of this github project is focused only on **exams** and **lessons** written by students.

As every student will have its own method to take notes (Hackmd, Pdf files, website, Picture in a Drive...), it will be easier and faster to just have a link, edited on a README.md, to the notes instead of regrouping everything in the same place with the same format

**Comment by utybo** [comment]
Got it, thanks for the clarification! I'll probably add this repo on epita.it then :)
